# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-23 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
    ]
